# Generated by Django 4.2.1 on 2023-06-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('discount', models.IntegerField(verbose_name='Процент скидки')),
                ('to_use', models.IntegerField(verbose_name='Сколько использований осталось')),
                ('is_for_everyone', models.BooleanField(default=False, verbose_name='Доступна ли всем?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, на которого назначена скидка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry', models.DateField(blank=True, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (3, 'Wallet')], default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешен ли платеж?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.discount', verbose_name='Скидка использованная в поездке')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payments', to='payment.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
